version: "3.9"
services:

  app_lr:
    container_name: ${CONTAINER_NAME}__lr
    build:
      context: ./conf
      dockerfile: laravel.Dockerfile
    image: ${CONTAINER_NAME}__lr
    ports:
      - ${LOCAL_PORT}:8000
    volumes:
      - ./html:/var/www/html
      - ./conf/httpd.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: /var/www/html
    restart: unless-stopped
    networks:
      - laravel

  db:
    container_name: ${CONTAINER_NAME}__db
    image: mysql:5.7
    ports:
      - ${DB_PORT}:80
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped
    networks:
      - laravel

  phpmyadmin:
    container_name: ${CONTAINER_NAME}__pma
    image: phpmyadmin/phpmyadmin:5.1
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_ROOT_PWD}
    restart: unless-stopped
    networks:
      - laravel

networks:
  laravel: